### ISSUE TITLE
Interface Segregation Principle

### ISSUE THREAD

**Issue by eferos93** [eferos93/quentin-sdm-exam#52]
Look and report here any violation

**Comment by eferos93** [comment]
I think that this principle (some details with an example at this [link](https://stackify.com/interface-segregation-principle/)) is not violated, but there is a sort of dependency problem between in the GUI version. If you look at the picture below, the implementation of `InputHandler` depends also on `OutputHandler`, in particular on the inner class `Message`.
What do you guys think, shall we keep it like this, or try to solve it in some way?

![interface segregation violation](https://user-images.githubusercontent.com/24605060/110113594-9e192c80-7db3-11eb-9b7c-3d73fcda0edd.png)

**Comment by demirbilek95** [comment]
This dependency seems strange at first, but I checked where we do this. This is mostly to notify the players after we get the input from them so I think it is not really a big deal so we can keep as it is. Otherwise how do we notify players? Maybe we can arrange GUIOutputHandler in this way, but this seems direct and easier and it doesn't look like spawning big problems.

**Comment by stefanosimonetto** [comment]
I agree to keep as it is, in my opinion it is not a violation of the principle
